### PR TITLE
Make cortex server to support both http and https

### PR DESCRIPTION
**Pull request by rhgb**
Necessary for debugging https sites.
Debugging CA certificate provided at the same time

### CODE REVIEW

**Comment by kaelzhang** [comment]
It's better to save ca cert by using something like

```sh
git clone git@yourdomain.com:ca.git ~/.cortex/ca
```

Do not hardcode ca into cortex project.

Maybe you could adds a new config key to cortex-profile to let user assign an arbitrary pathname of the ca file.

**Comment by rhgb** [comment]
ok, I'll provide a script for users to generate ca by themselves

**Comment by kaelzhang** [comment]
Plz give me your npm account

**Comment by rhgb** [comment]
https://www.npmjs.com/~rhgb

**Pull request merged**
